version: '3.7'
services:
  self-service:
    container_name: self-service
    image: self-service:dev
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
      - m2:/app/.m2
    ports:
      - 9000:9000
      - 9002:9002
volumes:
  m2:
